import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrivyAuthProvider from "../components/privy-auth/PrivyProvider";
import { OnchainkitProvider } from "../components/onchain-kit/OnchainKitProvider";
// import { ChakraProvider, defaultSystem } from "@chakra-ui/react";
import { Provider } from "../components/ui/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrivyAuthProvider>
          <Provider>
            <OnchainkitProvider>{children}</OnchainkitProvider>
          </Provider>
        </PrivyAuthProvider>
      </body>
    </html>
  );
}
